name: Build and run tests
on: 
  push:
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 7.0.x
          
      - name: Restore dependencies
        run: dotnet restore ./PathsOfPower.Tests/PathsOfPower.Tests.csproj
        
      - name: Build
        run: dotnet build ./PathsOfPower.Tests/PathsOfPower.Tests.csproj --no-restore
        
      - name: Test 
        run: dotnet test ./PathsOfPower.Tests/PathsOfPower.Tests.csproj --no-build --logger "html" --results-directory "test_results"

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: /home/runner/work/PathsOfPower/PathsOfPower/test_results/

        
        
      
        
  
