name: Spellcheck

on: 
  push:
  workflow_dispatch:

jobs:
  Spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v3
        with: 
          python-version: '3.11.0'

      - name: Install codespell
        run: python -m pip install codespell

      - name: Run codespell
        run: codespell
    
